apps/project/urls.py
#
# Import Django

from django.urls import path


#
# Import views

from .api import api_start_timer, api_stop_timer, api_discard_timer, api_get_tasks
from .views import projects, project, edit_project, task, edit_task, edit_entry, delete_entry, delete_untracked_entry, track_entry


#
# Url pattern

app_name = 'project'

urlpatterns = [
    path('', projects, name='projects'),
    path('<int:project_id>/', project, name='project'),
    path('<int:project_id>/<int:task_id>/', task, name='task'),
    path('<int:project_id>/<int:task_id>/edit/', edit_task, name='edit_task'),
    path('<int:project_id>/<int:task_id>/<int:entry_id>/edit/', edit_entry, name='edit_entry'),
    path('<int:project_id>/<int:task_id>/<int:entry_id>/delete/', delete_entry, name='delete_entry'),
    path('<int:project_id>/edit/', edit_project, name='edit_project'),
    path('delete_untracked_entry/<int:entry_id>/', delete_untracked_entry, name='delete_untracked_entry'),
    path('track_entry/<int:entry_id>/', track_entry, name='track_entry'),

    # API

    path('api/start_timer/', api_start_timer, name='api_start_timer'),
    path('api/stop_timer/', api_stop_timer, name='api_stop_timer'),
    path('api/discard_timer/', api_discard_timer, name='api_discard_timer'),
    path('api/get_tasks/', api_get_tasks, name='api_get_tasks'),
]

desideratum/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include

from apps.core.views import frontpage, privacy, terms, plans, signup

urlpatterns = [
    path('', frontpage, name='frontpage'),
    path('privacy/', privacy, name='privacy'),
    path('terms/', terms, name='terms'),
    # path('plans/', plans, name='plans'),
    path('admin/', admin.site.urls),


    #
    # Dashboard

    path('dashboard/', include('apps.dashboard.urls')),

    #
    # Auth

    path('signup/', signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='core/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/core/views.py
#
# Import functionality from Django

from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import render, redirect


#
#



#
# Views

def frontpage(request):
    return render(request, 'core/frontpage.html')

def privacy(request):
    return render(request, 'core/privacy.html')

def terms(request):
    return render(request, 'core/terms.html')

def plans(request):
    return render(request, 'core/plans.html')

def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)

        if form.is_valid():
            user = form.save()
            user.email = user.username
            user.save()

            login(request, user)

    else:
        form = UserCreationForm()

    return render(request, 'core/signup.html', {'form': form})

apps/core/templates/core/base.html
<!DOCTYPE html>

<html>
    <head>
        <!-- Meta -->
        <meta charset="utf-8">

        <!-- Title -->
        <title>{% block title %}{% endblock %}Minutos</title>

        <!-- CSS files -->
        <link rel="stylesheet" type="text/css" href="https://cdn.delivr.net/npm/bulma@0.9.1/css/bulma.min.css">
    </head>

    <body>
        <!-- Navbar -->
        <div id="navbar-app">
            <nav class="navbar{% if request.user.is_authenticated %} is-dark{% else %} is-light{% endif %}">
                <div class="navbar-brand">
                    <a href="/" class="navbar-item"><strong>Minutos</strong></a>
                </div>

                <div class="navbar-menu">
                    <div class="navbar-end">
                            <a href="{% url 'dashboard' %}" class="navbar-item">Dashboard</a>
                            <a href="{% url 'project:projects' %}" class="navbar-item">Projects</a>

                            <div class="navbar-item" v-if="!trackingTime">
                                <div class="buttons">
                                    <a class="button is-success" @click="startTimer()">
                                        <span class="icon"><i class="fas fa-stopwatch"></i></span>
                                        <span>Start</span>
                                    </a>
                                </div>
                            </div>

                            <div class="navbar-item" v-else>
                                <div class="buttons">
                                    <a class="button is-warning" @click="stopTimer()">
                                        <span class="icon"><i class="fas fa-stopwatch"></i></span>
                                        <span>[[ readableSeconds ]] (stop)</span>
                                    </a>
                                </div>
                            </div>


                        <div class="navbar-item">
                        </div>
                    </div>
                </div>
            </nav>

            <div class="modal" :class="{'is-active': showTrackingModal}">
                <div class="modal-background"></div>

                <div class="modal-card">
                    <div class="modal-card-head">
                        <p class="modal-card-title">Tracked time</p>
                    </div>

                    <div class="modal-card-body">
                        <p>You have tracked [[ readableSeconds ]]</p>
                    </div>

                    <footer class="modal-card-foot">
                        <button class="button is-primary" @click="addToTask()">Add to task</button>
                        <button class="button is-success" @click="addLater()">Add later</button>
                        <button class="button is-danger" @click="discardTimer()">Discard</button>
                    </footer>
                </div>
            </div>
        </div>
        <!-- End Navbar -->

        <!-- Main -->
        <section class="section">
            {% if messages %}
                {% for message in messages %}
                    <div class="notification is-info">{{ message }}</div>
                {% endfor %}
            {% endif %}

            {% block content %}
            {% endblock %}
        </section>
        <!-- End Main -->

        <!-- Footer -->
        <footer class="footer">
            <div class="columns is-multiline">
                <div class="column is-4">
                    <h2 class="subtitle">Minutos</h2>
                </div>

                <div class="column is-offset-6 is-2">
                    <ul>
                        <li><a href="#">Contact</a></li>
                        <li><a href="{% url 'privacy' %}">Privacy policy</a></li>
                        <li><a href="{% url 'terms' %}">Terms of service</a></li>
                    </ul>
                </div>

                <div class="column is-12 has-text-centered">
                    <p>Copyright (c) 2020</p>
                </div>
            </div>
        </footer>
        <!-- End Footer -->

        <!-- Scripts -->
        <script src="https://use.fontawesome.com/releases/v5.14.0/js/all.js"></script>
        <script src="https://unpkg.com/vue@next"></script>
        <script>
            var NavbarApp = {
                data() {
                    return {
                        seconds: {{ active_entry_seconds }},
                        trackingTime: false,
                        showTrackingModal: false,
                        timer: null,
                        entryID: 0,
                        startTime: '{{ start_time }}'
                    }
                },
                delimiters: ['[[', ']]'],
                methods: {
                    startTimer() {
                        fetch('/dashboard/projects/api/start_timer/', {
                            method: 'POST',
                            headers: {
                                'Content-Type': 'application/json',
                                'X-CSRFToken': '{{ csrf_token }}'
                            }
                        })
                        .then((response) => {
                            return response.json()
                        })
                        .then((result) => {
                            this.startTime = new Date()
                            this.trackingTime = true

                            this.timer = setInterval(() => {
                                this.seconds = (new Date() - this.startTime) / 1000
                            }, 1000)
                        })
                    },
                    stopTimer() {
                        fetch('/dashboard/projects/api/stop_timer/', {
                            method: 'POST',
                            headers: {
                                'Content-Type': 'application/json',
                                'X-CSRFToken': '{{ csrf_token }}'
                            }
                        })
                        .then((response) => {
                            return response.json()
                        })
                        .then((result) => {
                            this.entryID = result.entryID
                            this.showTrackingModal = true
                            this.trackingTime = false

                            window.clearTimeout(this.timer)
                        })
                    },
                    discardTimer() {
                        fetch('/dashboard/projects/api/discard_timer/', {
                            method: 'POST',
                            headers: {
                                'Content-Type': 'application/json',
                                'X-CSRFToken': '{{ csrf_token }}'
                            }
                        })
                        .then((response) => {
                            this.seconds = 0
                            this.showTrackingModal = false
                        })
                    },
                    addLater() {
                        this.seconds = 0
                        this.showTrackingModal = false
                    },
                    addToTask() {
                        console.log('addToTask')
                        window.location.href = '/dashboard/projects/track_entry/' + this.entryID + '/'
                    }
                },
                mounted() {
                    if (this.seconds !== 0) {
                        this.trackingTime = true
                        this.timer = setInterval(() => {
                            this.seconds = (new Date() - new Date(this.startTime)) / 1000
                        }, 1000)
                    }
                },
                computed: {
                    readableSeconds() {
                        const d = Number(this.seconds);
                        const h = Math.floor(d / 3600);
                        const m = Math.floor(d % 3600 / 60);
                        const s = Math.floor(d % 3600 % 60);

                        const hDisplay = h > 0 ? h + (h == 1 ? "h, " : "h, ") : "";
                        const mDisplay = m > 0 ? m + (m == 1 ? "m, " : "m, ") : "";
                        const sDisplay = s >= 0 ? s + (s == 1 ? "s" : "s") : "";

                        return hDisplay + mDisplay + sDisplay; 
                    }
                }
            }

            Vue.createApp(NavbarApp).mount('#navbar-app')
        </script>
        {% block scripts %}
        {% endblock %}
        <!-- End Scripts -->
    </body>
</html>

apps/core/templates/core/frontpage.html
{% extends 'core/base.html' %}

{% load static %}

{% block title %}Home | {% endblock %}

{% block content %}
<section class="hero is-medium is-light is-bold">
    <div class="hero-body">
        <div class="container">
            <h1 class="title">Welcome to Minutos</h1>
            <h2 class="subtitle">Time tracking made simple</h2>
        </div>
    </div>
</section>

<div class="container">
    <div class="columns">
        <div class="column is-8 is-offset-2">
            <div class="columns is-align-items mt-6">
                <div class="column is-4 image">
                    <img src="{% static 'images/features-tracktime.jpg' %}">
                </div>

                <div class="column is-8 text">
                    <h2 class="subtitle">Simple time tracking</h2>

                    <p>Time tracking made simple. Time tracking made simple. Time tracking made simple. Time tracking made simple. Time tracking made simple.</p>
                </div>
            </div>

            <div class="columns is-align-items mt-6">
                <div class="column is-8 text">
                    <h2 class="subtitle">Simple time tracking</h2>

                    <p>Time tracking made simple. Time tracking made simple. Time tracking made simple. Time tracking made simple. Time tracking made simple.</p>
                </div>

                <div class="column is-4 image">
                    <img src="{% static 'images/features-tracktime.jpg' %}">
                </div>
            </div>

            <div class="columns is-align-items mt-6">
                <div class="column is-4 image">
                    <img src="{% static 'images/features-tracktime.jpg' %}">
                </div>

                <div class="column is-8 text">
                    <h2 class="subtitle">Simple time tracking</h2>

                    <p>Time tracking made simple. Time tracking made simple. Time tracking made simple. Time tracking made simple. Time tracking made simple.</p>
                </div>
            </div>
        </div>
    </div>

    <div class="columns is-align-items-center mt-6">
        <div class="column is-4 is-offset-4 has-text-centered">
            <h2 class="subtitle">Let's get started</h2>

            <a href="{% url 'signup' %}" class="button is-success is-large">Get a free account</a>
        </div>
    </div>
</div>
{% endblock %}

apps/core/templates/core/terms.html
{% extends 'core/base.html' %}

{% block title %}Terms of service | {% endblock %}

{% block content %}
    <section class="hero is-medium is-light is-bold">
        <div class="hero-body">
            <div class="container">
                <h1 class="title">Terms of service</h1>
                <h2 class="subtitle">Some random information....</h2>
            </div>
        </div>
    </section>  
{% endblock %}